# Generated by Django 3.2.5 on 2021-08-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarruselApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageordentrabajo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
